#!/usr/bin/env bash
# Installing custom nginx response header

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var//www/html/index.html
sudo service nginx restart