#!/usr/bin/env bash
# Installing custom nginx response header

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var//www/html/index.html
sudo service nginx start
sudo sed -i "12i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
