#!/usr/bin/env bash
# INSTALLATION AND CONFIGURATION of HAProxy on a server

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy=1.8.\*

echo -e "
frontend http\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web-backend
backend web-backend\n
\tbalance roundrobin\n\
\tserver 921-web-01 35.231.181.131:80 check\n\
\tserver 921-web-02 35.227.25.5:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy reload