#!/usr/bin/env bash
# Script to listen the port 80
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/i"/etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/i" /etc/nginx/sites-enabled/default
sudo service nginx restart
