#!/usr/bin/env bash
#Bash script that changes the value of the ip in the localhost
cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts