#!/usr/bin/env bash
# Setting server in order to run Nginx as the user nginx
pkill apache2
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo sed -i '1a user nginx;' /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
