#!/usr/bin/env bash
# Setting server in order to run Nginx as the user nginx
pkill apache2
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 744 /etc/nginx/nginx.conf
chown nginx:nginx -R /etc/nginx
sudo -u nginx service nginx restart
